<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
     <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>LearnLineServer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    
    <!-- Newtonsoft pour la gestion du fichier JSON (base de données) -->
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
 <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
  </ItemGroup>

</Project>
